import type { Metadata } from "next";
import type { AppProps } from "next/app";
import localFont from "next/font/local";
import { AppProviders } from "@/contexts";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = localFont({
  src: "../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RythApp({ Component, pageProps: { ...pageProps } }: AppProps) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem={false}
      disableTransitionOnChange
    >
      <AppProviders>
        <main
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          <Component {...pageProps} />
          <Toaster />
        </main>
      </AppProviders>
    </ThemeProvider>
  );
}

export default RythApp;
